# Basic settings
title: Holan Blog
description: A blog about tech, life and my projects.
url: "https://holaneu.github.io" # replace with your actual GitHub username URL
baseurl: "" # leave blank if you are not using a project-specific subfolder

# Apply the Cayman theme
theme: jekyll-theme-cayman

# Optional - add author or other metadata
author: holaneu

# Optional - any plugins for additional functionality
plugins:
  - jekyll-feed # enables Atom/RSS feeds for your site
  - jekyll-tagging # enables tags if needed, ensure this plugin is allowed on GitHub Pages

# Optional - social links
social_links:
  twitter: your_twitter_username
  github: holaneu
